import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api, Evidence, Json, Notice, stamp, useResource } from "../components/Workspace";

export default function CommissioningPage() {
  const [date,setDate]=useState(new Date(Date.now()-86400000).toISOString().slice(0,10)),[form,setForm]=useState<Json|null>(null),[reviewed,setReviewed]=useState(false),[build,setBuild]=useState<Json|null>(null),[confirm,setConfirm]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const {data,error:loadError}=useResource(`/api/commissioning?date=${date}`);
  const {data:catalog}=useResource("/api/science/catalog");
  useEffect(()=>{if(data?.defaults){const d=data.defaults;setForm({source:"sun",tag:`sun_${date.replace(/-/g,"")}_review`,antennas:d.antennas,ref_ant:d.ref_ant,source_window:d.source_window,static_window:d.static_window,grid_mode:"exact",n_beams:512});setReviewed(false);}},[data,date]);
  useEffect(()=>{if(!build||build.state!=="running")return;const timer=setInterval(()=>api(`/api/commissioning/${build.id}`).then(setBuild).catch(e=>setError(e.message)),3000);return()=>clearInterval(timer);},[build?.id,build?.state]);
  const patch=(key:string,value:unknown)=>{setForm(f=>({...f,[key]:value}));setReviewed(false);};
  const stage=async()=>{setBusy(true);setError("");try{setBuild(await api("/api/commissioning/stage",{...form,reviewed}));setConfirm("");}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const start=async()=>{if(!build)return;setBusy(true);try{setBuild(await api(`/api/commissioning/${build.id}/start`,{confirm_id:confirm}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="workspace-page"><div className="page-heading"><p className="eyebrow">Commissioning · reviewed staging</p><h2>Build, inspect, then decide</h2><p className="muted">Sun calibration with explicit antenna selection. Building does not deploy weights, write the live registry or change restart defaults.</p></div><div className="workflow-links"><Link to="/cal/compare">Compare calibration-day phase</Link><Link to="/cal/transit">Independent Cyg A transit</Link><a href="http://localhost:8070/guides/generate-weights.html" target="_blank" rel="noreferrer">Calibration walkthrough</a></div>{(error||loadError)&&<Notice>{error||loadError}</Notice>}
    <div className="commission-grid"><section className="control-surface"><div className="field-row"><label>Solve date · UTC<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Calibrator<select disabled><option>Sun · default recipe</option></select></label></div>{form&&<><label>Product tag<input value={form.tag} onChange={e=>patch("tag",e.target.value)} maxLength={80}/></label>{["source_window","static_window"].map(key=><div className="field-row" key={key}><label>{key==="source_window"?"Solve start":"Static start"} · UTC<input type="datetime-local" value={form[key]?.[0]?.replace(" ","T").slice(0,16)||""} onChange={e=>patch(key,[e.target.value+":00Z",form[key][1]])}/></label><label>End · UTC<input type="datetime-local" value={form[key]?.[1]?.replace(" ","T").slice(0,16)||""} onChange={e=>patch(key,[form[key][0],e.target.value+":00Z"])}/></label></div>)}<h3>Reviewed antenna inclusion</h3><p className="muted">Changes apply only to a private build snapshot. Wiring truth and the current layout remain unchanged.</p><div className="antenna-checks">{(data?.defaults?.wired_antennas??[]).map((a:number)=>{const inp=catalog?.inputs?.find((i:Json)=>i.antenna===a);return <label key={a}><input type="checkbox" checked={form.antennas?.includes(a)} onChange={()=>patch("antennas",form.antennas.includes(a)?form.antennas.filter((x:number)=>x!==a):[...form.antennas,a])}/>{inp?.station??`Ant ${a}`}<small>Ant {a}</small></label>;})}</div><label>Reference antenna<select value={form.ref_ant} onChange={e=>patch("ref_ant",Number(e.target.value))}>{form.antennas?.map((a:number)=><option key={a} value={a}>Ant {a}</option>)}</select></label><label className="review-confirm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the solve/static windows, antenna selection and resource budget.</label><button className="primary" disabled={!reviewed||busy} onClick={stage}>{busy?"Working…":"Stage reviewed recipe"}</button></>}{!form&&!loadError&&<p>Computing source-window defaults…</p>}<Evidence value={data?.budget}/></section>
    <section>{(data?.warnings??[]).map((w:string,i:number)=><Notice key={i}>{w}</Notice>)}{build?<article className="build-review"><span className="eyebrow">{build.state}</span><h3>{build.recipe?.tag??build.id}</h3><p className="muted">{stamp(build.created_utc)} · {build.id}</p>{(build.warnings??[]).map((w:string,i:number)=><Notice key={i}>{w}</Notice>)}<Evidence value={{recipe:build.recipe,budget:build.budget,command:build.command,layout_sha256:build.layout_sha256}}/>{build.state==="staged"&&<><label>To start the bounded build, type its ID<input value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder={build.id}/></label><button className="primary" disabled={busy||confirm!==build.id} onClick={start}>Start this calibration build</button></>}<p><button disabled>Deployment disabled</button> <button disabled>Restart defaults disabled</button></p>{build.error&&<Notice>{build.error}</Notice>}{build.state!=="staged"&&<a href={`/api/commissioning/${build.id}/log`} target="_blank" rel="noreferrer">Build log</a>}<div className="history-grid">{(build.artifacts??[]).map((a:Json)=><figure className="plot-surface" key={a.id}>{a.kind==="image"&&<a href={a.url} target="_blank" rel="noreferrer"><img src={a.url} alt={a.name}/></a>}<a href={a.url} download>{a.name}</a></figure>)}</div></article>:<div className="empty-science"><h3>Review before spending compute</h3><p>Staging saves the exact recipe and layout snapshot. A separate confirmation starts the canonical builder and its diagnostic notebook.</p><p>Fresh products still require scientific review. Higher rank-1 alone does not establish better beam sensitivity.</p></div>}<h3>Local staged builds</h3>{(data?.builds??[]).map((b:Json)=><p key={b.id}><button onClick={()=>{setBuild(b);setConfirm("");}}>{b.recipe?.tag??b.id}</button> · {b.state}</p>)}</section></div><section className="control-surface"><h3>Recorded calibration diagnostics</h3><p className="muted">Existing files adjacent to the ledger-recorded products. Use the report or notebook to identify the solve window and antenna selection; file proximity alone does not prove a live deployment.</p><details><summary>Browse {(data?.recorded_diagnostics??[]).length} saved plots, reports and notebooks</summary><div className="history-grid">{(data?.recorded_diagnostics??[]).map((a:Json)=><figure className="plot-surface" key={a.id}>{a.kind==="image"&&<a href={a.url} target="_blank" rel="noreferrer"><img loading="lazy" src={a.url} alt={a.name}/></a>}<a href={a.url} target="_blank" rel="noreferrer">{a.name}</a></figure>)}</div></details></section></div>;
}
