import MonitoringOverview from "../components/MonitoringOverview";
import { Link } from "react-router-dom";
import { Evidence, Json, Notice, stamp, useResource } from "../components/Workspace";
import { Geometry, Overview } from "./ObservationPage";

export default function OperationsPage() {
  const {data,error}=useResource("/api/observation",30000);
  if(!data)return <Notice>{error||"Loading observation and injection evidence…"}</Notice>;
  const inj=data.injections??{},c=inj.counts??{},misses:Json[]=inj.misses??[], recent:Json[]=inj.recent??[];
  const latestReplay=recent.find(i=>i.replay?.artifacts?.png?.available);
  return <div className="workspace-page"><div className="observatory-line"><span>Owens Valley Radio Observatory · {data.location?.latitude_deg?.toFixed(3)}°, {data.location?.longitude_deg?.toFixed(3)}°</span><span>{stamp(data.clock?.utc)} · LST {data.clock?.lst}</span></div><div className="page-heading"><p className="eyebrow">Current observation · {data.observation?.state?.value??"unknown"}</p><h2>Science and search recovery</h2><p className="muted">{data.observation?.id??"Observation identity unavailable"} · OVRO local {data.clock?.local?.replace("T"," ")}</p></div>{error&&<Notice>Refresh failed. Showing the last received evidence. {error}</Notice>}
    <div className="stat-strip"><div><span>Recovered · rolling 24 h</span><strong>{inj.status==="unavailable"?"Unavailable":`${c.recovered??"?"} / ${c.completed_fired??"?"}`}</strong></div><div><span>T1 / T2 misses</span><strong>{c.missed_t1??"?"} / {c.missed_t2??"?"}</strong></div><div><span>Firing failures / pending</span><strong>{c.fire_failed??"?"} / {c.pending??"?"}</strong></div><div><span>Visibility data age</span><strong>{data.observation?.vis_age?.value==null?"Unknown":`${Math.round((data.observation.vis_age.value+(data.observation.vis_age.age_s??0))/60)} min`}</strong></div></div>
    <div className="workflow-links"><Link to="/review">Review every miss</Link><Link to="/search">Inspect T1 / RFI</Link><Link to="/vis">Inspect baseline phase</Link><Link to="/cal/compare">Compare calibration day</Link></div>
    <MonitoringOverview/><div className="operations-grid"><section><div className="section-heading"><h3>Injection review</h3><a href="http://localhost:8050/" target="_blank" rel="noreferrer">T2 / T3 viewer</a></div><p className="muted">{stamp(inj.window_start_utc)} → {stamp(inj.as_of_utc)}. Recorded outcomes, not inferred causes.</p>{inj.status!=="ok"&&<Notice>{inj.status??"Unknown injection evidence"} · {inj.error??"Check coverage below."}</Notice>}
      <div className="table-scroll"><table className="science-table"><thead><tr><th>Trial · UTC</th><th>Outcome</th><th>Beam / DM</th><th>Recorded reason</th></tr></thead><tbody>{recent.map(i=><tr key={i.file_id}><td><Link to="/review">{i.file_id}</Link><small>{stamp(i.inject_utc)}</small></td><td className={i.outcome?.startsWith("miss")?"caution":""}>{i.outcome??"Pending / legacy"}</td><td>{i.beam} / {Number(i.dm).toFixed(1)}</td><td>{i.fail_reason||"—"}{i.replay?.artifacts?.png?.available&&<small><a href={i.replay.artifacts.png.url} target="_blank" rel="noreferrer">Saved synthetic replay</a></small>}</td></tr>)}</tbody></table></div><p className="muted">{misses.length} misses in the retained review window. Recovery is established by search matching; a replay is synthetic evidence, not a recording of live recovery.</p><h3>Seven-day recovery history · UTC days</h3><div className="table-scroll"><table className="science-table"><thead><tr><th>Date</th><th>Recovered / completed fired</th><th>T1 / T2 misses</th><th>Fire failed / pending</th></tr></thead><tbody>{(inj.trend??[]).map((d:Json)=><tr key={d.date_utc}><td>{d.date_utc}</td><td>{d.recovered} / {d.completed_fired}</td><td>{d.missed_t1} / {d.missed_t2}</td><td>{d.fire_failed} / {d.pending}</td></tr>)}</tbody></table></div><Evidence value={{source:inj.source,status:inj.status,counts_complete:inj.counts_complete,window_start:inj.window_start_utc}}/></section>
      <aside><Geometry data={data as Overview}/>{latestReplay&&<figure className="plot-surface"><figcaption>Saved replay · {latestReplay.file_id}</figcaption><a href={latestReplay.replay.artifacts.png.url} target="_blank" rel="noreferrer"><img src={latestReplay.replay.artifacts.png.url} alt="Saved synthetic injection replay"/></a><a href={latestReplay.replay.artifacts.png.url} download>Download replay PNG</a></figure>}</aside></div></div>;
}
