import { useState } from "react";
import { api, Evidence, Json, Notice, ProductImage, stamp, useResource } from "../components/Workspace";

export default function ReviewPage() {
  const [version,setVersion]=useState(0),[offset,setOffset]=useState(0),[filter,setFilter]=useState("queued"),[message,setMessage]=useState("");
  const {data,error}=useResource(`/api/review?v=${version}&offset=${offset}`,30000);
  const items:Json[]=data?.items??[];
  const request=async(item:Json)=>{try {await api(`/api/review/${encodeURIComponent(item.id)}/request`,{}, {"X-CASM-Review-CSRF":data?.csrf_token});setMessage("Investigation requested. Evidence is saved; no autonomous worker or Slack integration is enabled.");setVersion(v=>v+1);}catch(e){setMessage((e as Error).message);}};
  return <div className="workspace-page"><div className="page-heading"><p className="eyebrow">Human review</p><h2>Investigation queue</h2><p className="muted">Injection misses and marked plots wait here. You decide what to investigate; nothing runs automatically.</p></div>{(error||message)&&<Notice>{error||message}</Notice>}<div className="choice-row">{["queued","requested","all"].map(v=><button className={filter===v?"active":""} key={v} onClick={()=>setFilter(v)}>{v==="queued"?"Awaiting review":v==="requested"?"Requested":"All evidence"}</button>)}<button onClick={()=>setVersion(v=>v+1)}>Refresh</button></div>
    {data?.saved_truncated&&<Notice>Showing a page of {data.saved_total} retained items. Use the page controls to inspect the rest.</Notice>}<div className="choice-row">{offset>0&&<button onClick={()=>setOffset(Math.max(0,offset-2000))}>Previous page</button>}{data?.next_offset!=null&&<button onClick={()=>setOffset(data.next_offset)}>Next page</button>}</div>{data?.source_status&&<Evidence value={data.source_status}/>}
    <div className="review-list">{items.filter(i=>filter==="all"||(i.state??i.status??"queued")===filter).map(i=><article className="review-item" key={i.id}><div><span className="eyebrow">{i.state??i.status??"queued"} · {i.kind??"investigation"}</span><h3>{i.title??i.id}</h3><p>{i.note||i.summary||i.reason||i.provenance?.recorded_evidence?.fail_reason||"Recorded cause unresolved; inspect the evidence."}</p><p className="muted">{stamp(i.created_at??i.created_utc??i.inject_utc)}</p>{(i.saved_plot_url??i.plot_url)&&<div className="review-thumbnail"><ProductImage url={i.saved_plot_url??i.plot_url} label="Saved evidence for this investigation"/></div>}<Evidence value={{selection:i.selection,provenance:i.provenance,evidence:i.evidence}}/></div><div>{(i.state??i.status??"queued")==="queued"?<button className="primary" onClick={()=>request(i)}>Request investigation</button>:<p className="muted">Awaiting investigator</p>}</div></article>)}</div>{data&&!items.length&&<p>No review items in the available evidence window.</p>}<p className="muted">“Requested” is a durable handoff, not a claim that analysis is running. Downloadable records preserve selection, provenance and the human question.</p><a href="/api/review" target="_blank" rel="noreferrer">Open machine-readable queue</a></div>;
}
