import { useState } from "react";
import { api, initialWindow, isoInput, Json, LOCAL, Notice, ProductPlots, TimeWindow, useResource } from "../components/Workspace";

export default function SnapWorkspacePage() {
  const {data,error:inventoryError}=useResource("/api/snaps/boards");
  const {data:acquisition,error:acquisitionError}=useResource("/api/snap-workspace/acquisition",10000);
  const {data:figures,error:figureError}=useResource(`/api/snap-workspace/board-overview?v=${acquisition?.latest_job?.finished??""}`,60000);
  const [reading,setReading]=useState(false),[receipt,setReceipt]=useState("");
  const [window,setWindow]=useState(initialWindow(1)),[packet,setPacket]=useState(""),[fmin,setFmin]=useState("390.625"),[fmax,setFmax]=useState("484.375"),[product,setProduct]=useState<Json|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[mode,setMode]=useState("board");
  const inputs:Json[]=(data?.boards??[]).flatMap((b:Json)=>(b.inputs??[]).filter((i:Json)=>i.packet_idx!=null&&i.functional).map((i:Json)=>({...i,feng_id:b.feng_id})));
  const selected=packet||String(inputs[0]?.packet_idx??"");
  const acquire=async()=>{setReading(true);setError("");try{const status=await api("/api/snap-workspace/acquisition");const ips=(data?.boards??[]).filter((b:Json)=>b.role==="antenna").map((b:Json)=>b.ip);if(!ips.length)throw new Error("No configured antenna boards available");const result=await api("/api/snap-workspace/acquire",{ips,confirm:true},{"X-CASM-Snap-CSRF":status.csrf_token});setReceipt(`Read queued · job ${result.job_id}. Spectra update after acquisition completes.`);}catch(e){setError((e as Error).message);}finally{setReading(false);}};
  const render=async()=>{setBusy(true);setError("");try{setProduct(await api("/api/snap-workspace/render",{packet_idx:Number(selected),t0:isoInput(window.t0),t1:isoInput(window.t1),fmin:Number(fmin),fmax:Number(fmax)}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="workspace-page"><div className="page-heading"><p className="eyebrow">Antenna signal chain</p><h2>SNAP spectra and history</h2><p className="muted">Transmitted-band history and saved full-board spectra are different measurements. Opening this page never reads hardware.</p></div><div className="control-surface"><div className="field-row"><button className="primary" disabled={reading||!acquisition?.manual_enabled||!!acquisition?.manual_refusal} onClick={acquire}>{reading?"Submitting read…":"Get latest spectra"}</button><span className="muted">Configured automatic interval: {acquisition?acquisition.configured_interval_s/3600:"…"} h</span></div>{acquisition?.due&&<Notice>Scheduled spectra are overdue. A configured interval does not establish a successful acquisition.</Notice>}{acquisition?.latest_job&&<p className="muted">Latest read job {acquisition.latest_job.id}: {acquisition.latest_job.state}</p>}{acquisition?.manual_refusal&&<p role="status">{acquisition.manual_refusal.detail}</p>}{receipt&&<p role="status">{receipt}</p>}{acquisitionError&&<Notice>{acquisitionError}</Notice>}<p className="muted">Diagnostic spectra acquisition only: no programming, EQ changes or synchronization. Navigation reads saved products.</p></div><div className="choice-row"><button className={mode==="history"?"active":""} onClick={()=>setMode("history")}>Selected input history</button><button className={mode==="board"?"active":""} onClick={()=>setMode("board")}>Saved 4096-channel board overview</button></div>{(error||inventoryError)&&<Notice>{error||inventoryError}</Notice>}{mode==="history"?<><div className="control-surface"><TimeWindow value={window} onChange={setWindow}/><div className="field-row"><label>Antenna / station<select value={selected} onChange={e=>setPacket(e.target.value)}>{inputs.map(i=><option key={i.packet_idx} value={i.packet_idx}>{i.station} · Ant {i.antenna} · S{i.feng_id} A{i.adc}</option>)}</select></label><label>Min · MHz<input type="number" step="0.01" value={fmin} onChange={e=>setFmin(e.target.value)}/></label><label>Max · MHz<input type="number" step="0.01" value={fmax} onChange={e=>setFmax(e.target.value)}/></label><button className="primary" disabled={busy||!selected} onClick={render}>{busy?"Rendering cached input…":"Render history"}</button></div></div>{product&&<ProductPlots product={product}/>}</>:<>{figureError&&<Notice>{figureError} Previous spectra may be stale.</Notice>}{figures?<><div className="control-surface"><h3>Acquisition times · OVRO local</h3>{(figures.provenance?.boards??[]).map((b:Json)=><p key={b.ip}>SNAP {b.feng_id} · {b.ts?new Date(b.ts*1000).toLocaleString("en-US",{timeZone:LOCAL,timeZoneName:"short"}):"No saved read"}{!b.shard_id?" · no spectrum available":""}</p>)}</div><ProductPlots product={figures}/></>:<Notice>Loading saved full-board spectra…</Notice>}</>}</div>;
}
