import { useState } from "react";
import { api, Evidence, initialWindow, isoInput, Json, Notice, ProductPlots, TimeWindow, useResource } from "../components/Workspace";

export default function SnapWorkspacePage() {
  const {data,error:inventoryError}=useResource("/api/snaps/boards");
  const {data:figures}=useResource("/api/figures/snaps/manifest?set=all12",60000);
  const [window,setWindow]=useState(initialWindow(1)),[packet,setPacket]=useState(""),[fmin,setFmin]=useState("390.625"),[fmax,setFmax]=useState("484.375"),[product,setProduct]=useState<Json|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[mode,setMode]=useState("history");
  const inputs:Json[]=(data?.boards??[]).flatMap((b:Json)=>(b.inputs??[]).filter((i:Json)=>i.packet_idx!=null&&i.functional).map((i:Json)=>({...i,feng_id:b.feng_id})));
  const selected=packet||String(inputs[0]?.packet_idx??"");
  const render=async()=>{setBusy(true);setError("");try{setProduct(await api("/api/snap-workspace/render",{packet_idx:Number(selected),t0:isoInput(window.t0),t1:isoInput(window.t1),fmin:Number(fmin),fmax:Number(fmax)}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="workspace-page"><div className="page-heading"><p className="eyebrow">Antenna signal chain</p><h2>SNAP spectra and history</h2><p className="muted">Transmitted-band history and saved full-board spectra are different measurements. Opening this page never reads hardware.</p></div><div className="choice-row"><button className={mode==="history"?"active":""} onClick={()=>setMode("history")}>Selected input history</button><button className={mode==="board"?"active":""} onClick={()=>setMode("board")}>Saved 4096-channel board overview</button></div>{(error||inventoryError)&&<Notice>{error||inventoryError}</Notice>}{mode==="history"?<><div className="control-surface"><TimeWindow value={window} onChange={setWindow}/><div className="field-row"><label>Antenna / station<select value={selected} onChange={e=>setPacket(e.target.value)}>{inputs.map(i=><option key={i.packet_idx} value={i.packet_idx}>{i.station} · Ant {i.antenna} · S{i.feng_id} A{i.adc}</option>)}</select></label><label>Min · MHz<input type="number" step="0.01" value={fmin} onChange={e=>setFmin(e.target.value)}/></label><label>Max · MHz<input type="number" step="0.01" value={fmax} onChange={e=>setFmax(e.target.value)}/></label><button className="primary" disabled={busy||!selected} onClick={render}>{busy?"Rendering cached input…":"Render history"}</button></div></div>{product&&<ProductPlots product={product}/>}</>:<><p className="muted">Saved collector product. Acquisition is normally much less frequent than visibility integrations; inspect its timestamps.</p>{figures?<figure className="plot-surface"><img src={`/api/figures/snaps/all12/spectra_board@2x.png?v=${figures.rendered_utc??""}`} alt="Saved full-board SNAP spectra with scientific frequency axes"/><a download href="/api/figures/snaps/all12/spectra_board@2x.png">Download full-board PNG</a><Evidence value={figures}/></figure>:<Notice>Saved full-board overview unavailable.</Notice>}</>}</div>;
}
