import { useState } from "react";
import { Evidence, Json, Notice, useResource } from "../components/Workspace";

export default function SourceHistoryPage() {
  const [query,setQuery]=useState("B0329"),[search,setSearch]=useState("B0329"),[filter,setFilter]=useState("all");
  const {data,error}=useResource(`/api/sources?q=${encodeURIComponent(search)}`);
  const attempts:Json[]=(data?.sources??[]).flatMap((s:Json)=>s.attempts??[]);
  return <div className="workspace-page"><div className="page-heading"><p className="eyebrow">Pulsar observing history</p><h2>Source history</h2><p className="muted">The full canonical attempt history, including non-detections and withdrawn claims. No new folds or detections are generated here.</p></div><form className="field-row control-surface" onSubmit={e=>{e.preventDefault();setSearch(query);}}><label>Source<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="B0329+54"/></label><button className="primary">Search history</button><label>Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All attempts</option><option value="plots">With saved plots</option><option value="retracted">Contains retraction</option></select></label></form>{error&&<Notice>{error}</Notice>}{!data&&!error&&<Notice>Reading canonical history and bounded saved-plot inventory…</Notice>}<div className="history-grid">{attempts.filter(a=>filter==="all"||(filter==="plots"?a.artifacts.length:a.contains_retraction)).map(a=><article className="history-entry" key={a.id}><span className="eyebrow">{a.source} · {a.status?.replace(/_/g," ")}</span><h3>{a.date}</h3>{a.contains_retraction&&<Notice>Contains a retracted claim. Read the qualification.</Notice>}{a.artifacts?.length?<a href={a.artifacts[0].url} target="_blank" rel="noreferrer"><img loading="lazy" className="history-plot" src={a.artifacts[0].url} alt={`Saved fold evidence for ${a.date}`}/></a>:<p className="empty-plot">No accessible saved PNG linked to this attempt.</p>}<p className="ledger-text">{a.outcome}</p><details><summary>Configuration and all saved plots ({a.artifacts?.length??0})</summary><p>{a.config}</p><p className="muted">{a.directory}</p>{(a.artifacts??[]).map((im:Json)=><figure className="plot-surface" key={im.id}><a href={im.url} target="_blank" rel="noreferrer"><img loading="lazy" className="history-plot" src={im.url} alt={im.name}/></a><a href={im.url} download>{im.name}</a></figure>)}<Evidence value={{source:a.provenance,note:a.evidence_note,scan_partial:a.artifact_scan_partial}}/></details></article>)}</div>{data&&!attempts.length&&<Notice>No matching source in the indexed canonical history.</Notice>}<p className="muted">{data?.note}</p></div>;
}
