import { useState } from "react";
import { Link } from "react-router-dom";
import { api, Evidence, initialWindow, isoInput, Json, Notice, SaveInvestigation, TimeWindow } from "../components/Workspace";

export default function T1Page() {
  const [window,setWindow]=useState(initialWindow()),[data,setData]=useState<Json|null>(null),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>{setBusy(true);setError("");try{const q=new URLSearchParams({t0:isoInput(window.t0),t1:isoInput(window.t1)}).toString();setData(await api("/api/t1?"+q));setQuery(q);}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="workspace-page"><div className="page-heading"><p className="eyebrow">Search pressure and interference</p><h2>T1 · Hella candidates per gulp</h2><p className="muted">Inspect emitted candidates, beam occupancy, dispersion measure and width. Explicit cap warnings are separate evidence.</p></div><div className="control-surface"><TimeWindow value={window} onChange={setWindow}/><button className="primary" disabled={busy} onClick={load}>{busy?"Loading bounded search evidence…":"Inspect interval"}</button></div>{error&&<Notice>{error}</Notice>}{data&&<><div className="stat-strip"><div><span>Data status</span><strong>{data.status??"See coverage"}</strong></div><div><span>10k limit</span><strong>Per gulp</strong></div><div><span>Beam skipping</span><strong>Not inferred</strong></div></div>{(data.warnings??[]).map((w:string,i:number)=><Notice key={i}>{w}</Notice>)}<figure className="plot-surface"><figcaption>T1 distributions · selected interval</figcaption><a href={data.plot_url??`/api/t1/plot.png?${query}`} target="_blank" rel="noreferrer"><img src={data.plot_url??`/api/t1/plot.png?${query}`} alt="T1 candidates per gulp, beam versus time, DM versus time and width distribution"/></a><div className="plot-actions"><a download href={data.plot_url??`/api/t1/plot.png?${query}`}>Download PNG</a><a download href={`/api/t1?${query}`}>Download evidence JSON</a><Link to={`/vis?${query}`}>Inspect these times in visibilities</Link></div><SaveInvestigation selection={{kind:"t1",...Object.fromEntries(new URLSearchParams(query))}} provenance={data.coverage??data.provenance??{}} plotUrl={data.plot_url??`/api/t1/plot.png?${query}`}/></figure><section className="control-surface"><h3>Recorded cap warnings</h3><p>{data.note}</p><p className="muted">{data.coverage_note}</p><p className="muted">Log status: {data.log?.status??"unknown"} · {data.log?.first_utc??"unknown start"} to {data.log?.last_utc??"unknown end"}. A bounded log tail does not cover a whole day.</p><div className="table-scroll"><table><thead><tr><th>UTC</th><th>Raw peaks</th><th>Processed / instance beams</th><th>Log evidence</th></tr></thead><tbody>{(data.log?.cap_warnings??[]).map((w:Json,i:number)=><tr key={i}><td>{w.utc}</td><td>{w.raw_peaks??"unknown"}</td><td>{w.processed_beams??"?"} / {w.instance_beams??"?"}</td><td><code>{w.log_line}</code></td></tr>)}</tbody></table></div>{!data.log?.cap_warnings?.length&&<p>No cap warnings found in the inspected log coverage. This does not establish a cap-free interval.</p>}<details><summary>Full evidence and coverage</summary><Evidence value={data}/></details></section></>} {!data&&!busy&&<div className="empty-science"><h3>Start with the interval that needs attention</h3><p>The 10k raw-peak cap is not the same as 10k emitted clustered candidates. Incomplete log coverage cannot establish a cap-free day.</p></div>}</div>;
}
