import { useState } from "react";
import { api, initialWindow, isoInput, Json, Notice, ProductPlots, TimeWindow, useResource } from "../components/Workspace";

export default function TransitPage() {
  const {data:catalog,error:catalogError}=useResource("/api/science/catalog");
  const {data:obs}=useResource("/api/observation");
  const [window,setWindow]=useState(initialWindow(2)),[cal,setCal]=useState(""),[alt,setAlt]=useState("86.5"),[az,setAz]=useState("0"),[controlAlt,setControlAlt]=useState("70"),[controlAz,setControlAz]=useState("90"),[fmin,setFmin]=useState("410"),[fmax,setFmax]=useState("470"),[product,setProduct]=useState<Json|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const render=async()=>{setBusy(true);setError("");try{setProduct(await api("/api/science/transit",{calibration_id:cal||catalog?.transit_calibrations?.[0]?.id,recorded_product_id:obs?.deployment?.product_id,t0:isoInput(window.t0),t1:isoInput(window.t1),fixed_alt_deg:Number(alt),fixed_az_deg:Number(az),control_alt_deg:Number(controlAlt),control_az_deg:Number(controlAz),fmin:Number(fmin),fmax:Number(fmax)}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  return <div className="workspace-page"><div className="page-heading"><p className="eyebrow">Independent stationary-source check</p><h2>Cyg A · beamformed visibility transit</h2><p className="muted">Fixed selected and control directions, native-channel cached visibilities and an explicitly selected calibration. No tracking-beam substitution.</p></div>{(error||catalogError)&&<Notice>{error||catalogError}</Notice>}<div className="control-surface"><TimeWindow value={window} onChange={setWindow}/><label>Calibration evidence<select value={cal} onChange={e=>setCal(e.target.value)}><option value="">Select current ledger reference</option>{(catalog?.transit_calibrations??[]).map((c:Json)=><option key={c.id} value={c.id}>{c.path}</option>)}</select></label><div className="field-row">{[["Fixed altitude · deg",alt,setAlt],["Fixed azimuth · deg",az,setAz],["Control altitude · deg",controlAlt,setControlAlt],["Control azimuth · deg",controlAz,setControlAz],["Min frequency · MHz",fmin,setFmin],["Max frequency · MHz",fmax,setFmax]].map(([label,value,setter])=><label key={String(label)}>{String(label)}<input type="number" step="0.1" value={String(value)} onChange={e=>(setter as (s:string)=>void)(e.target.value)}/></label>)}</div><Notice>Review pointing and time bounds before rendering. Initial directions are editable examples, not an approved null-beam choice. A mixed-calibration deployed product is not represented by one ledger calibration.</Notice><button className="primary" disabled={busy||!catalog?.transit_calibrations?.length} onClick={render}>{busy?"Computing bounded stationary-beam evidence…":"Render independent transit"}</button></div>{product&&<ProductPlots product={product}/>}<p className="muted">At most two hours and 32 antennas. Missing native cache is unavailable, never replaced with averaged baseline amplitudes. Model and measured amplitude use explicitly different units; no automatic pass/fail verdict.</p></div>;
}
